---
  el:
    hosts:
      centos:
        ansible_connection: docker
  deb:
    hosts:
      ubuntu:
        ansible_connection: docker

  localhost:
    hosts:
      localhost:
          ansible_connection: local
